name: Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-firefox
        ports:
          - 4444:4444

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quiz_pengupil
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Start PHP server
      run: php -S localhost:3000 -t .

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo "Waiting for database connection..."
          sleep 2
        done

    - name: Import database
      env:
        MYSQL_PWD: root
      run: |
        mysql -h 127.0.0.1 -u root quiz_pengupil < db/quiz_pengupil.sql

    - name: Run Selenium tests
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: |
        python testlogin.py
